FROM ghcr.io/bento-platform/bento_base_image:python-debian-latest

WORKDIR /app

COPY requirements.txt .
COPY requirements.dev.txt .
RUN pip install -r requirements.txt

COPY . .

ENV CHORD_DEBUG=True
ENTRYPOINT ["python3", "run.py"]
